//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperHeroAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agrupaciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Agrupaciones()
        {
            this.Misiones_Agrupaciones = new HashSet<Misiones_Agrupaciones>();
            this.Superheroes = new HashSet<Superheroes>();
        }
    
        public int AgrupacionesID { get; set; }
        public string Nombre { get; set; }
        public string Nombre_integrantes { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Misiones_Agrupaciones> Misiones_Agrupaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Superheroes> Superheroes { get; set; }
    }
}
