//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperHeroAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Misiones_Agrupaciones
    {
        public int MisionesCodigo { get; set; }
        public int AgrupacionID { get; set; }
        public Nullable<System.DateTime> FechaAsignacion { get; set; }
    
        public virtual Agrupaciones Agrupaciones { get; set; }
        public virtual Misiones Misiones { get; set; }
    }
}
