//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperHeroAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SuperHeroesEntities1 : DbContext
    {
        public SuperHeroesEntities1()
            : base("name=SuperHeroesEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Agrupaciones> Agrupaciones { get; set; }
        public virtual DbSet<Misiones> Misiones { get; set; }
        public virtual DbSet<Superheroes> Superheroes { get; set; }
        public virtual DbSet<Superpoderes> Superpoderes { get; set; }
        public virtual DbSet<TipoMision> TipoMision { get; set; }
        public virtual DbSet<Misiones_Agrupaciones> Misiones_Agrupaciones { get; set; }
        public virtual DbSet<Superheroes_Misiones> Superheroes_Misiones { get; set; }
        public virtual DbSet<Superheroes_Superpoderes> Superheroes_Superpoderes { get; set; }
    }
}
